steps:
 # install dependencies for angular app
 - name: "gcr.io/cloud-builders/npm:node-10.10.0"
   args: ['install']
   
 # build production ready frontend angular app
 - name: "gcr.io/cloud-builders/npm:node-10.10.0"
   args: [run, ng, "--", build, "--prod"]

 
